version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - gocritic
    - misspell
    - nilerr
    - reassign
    - unconvert
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - performance
    misspell:
      locale: US
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
    paths:
      - .*_templ\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
